from pathlib import Path
from docx import Document
from docx.shared import Pt
import json,shutil
P=Path(__file__).resolve().parent
source=P.parent/'redshift_paper/temporal_redshift_paper.docx'
shutil.copy2(source,P/'original_paper.docx')
doc=Document(source);r=json.loads((P/'results.json').read_text())
for p in doc.paragraphs:
 if p.text=='Research hypothesis • 8 September 2026':p.text='Research hypothesis • Revised 8 September 2026 • Observational extension'
 if p.text.startswith('We investigate a universe with fixed spatial geometry'):
  p.add_run(' A subsequent derived-data reanalysis of 1,504 DES supernovae reproduces a duration exponent b=1.0029 ± 0.0048 (formal statistical error), while a 43-channel FIRAS residual check finds no significant y-type distortion. These establish compatibility of specific observable predictions, not evidence selecting the proposed field over other mechanisms. A screened ray model resolves endpoint normalization at the geometric-optics level; its microscopic completion remains open.')
 if p.text=='9. Conclusion':
  anchor=p; p.text='12. Conclusion'
 if p.text.startswith('The exponential law follows from specified composition assumptions and can be realized'):
  p.text='The original nearby-galaxy experiment remains inconclusive between the temporal law and its reference. The observational extension supports retaining whole-signal stretching as a required behavior and coherent thermal transport as a conditional spectral mechanism. Neither the DES widths nor the FIRAS monopole identifies the field, determines its energy reservoir or establishes non-expansion. A screened geometric-optics construction provides an explicit source-to-detector consistency result, but a common matter, radiation and gravitational action remains necessary. No Big Bang is assumed here; an earlier equilibrium in fixed space is a possible initial condition, not an inferred thermal origin. Directional CMB structure and galaxy rotation remain unpredicted.'
# Append new elements, then relocate together immediately before conclusion.
before=set(doc.element.body)
def h(t):doc.add_heading(t,level=1)
def p(t,style=None):doc.add_paragraph(t,style)
def eq(t):p(t,'Equation')
h('9. Observational extension: signal stretching and spectral shape')
p('This revision distinguishes three evidence levels: reanalysis of released derived measurements, comparison with published summary measurements, and synthetic checks of equations. None is described as an independent raw-data discovery. The original 164-group split has already been inspected; subsequent alternatives fitted to its training subset are exploratory. Photon energy alone, full-signal transport and a positive exponential optical history give final-test RMSE values of 413.47, 412.44 and 411.54 km/s, respectively. Their sub-2 km/s separation does not select a physical history.')
p('DES event widths. We downloaded the g, r, i and z band width products from the authors’ DES-Time-Dilation repository [7]. We retained finite positive uncertainties smaller than the measured widths, matching the published plotting selection, and averaged available bands per event with the authors’ quadrature error prescription. This yields 1,504 unique supernovae. Fitting w=(1+z)^b gives b=1.002877 ± 0.004825 and χ²/(N−1)=1.44143, reproducing the published result. A 400-resample event bootstrap gives a 95% interval of 0.99312–1.01384; shared-reference covariance and systematic errors are not included in that interval.')
p('Separate band fits give b=1.0212 ± 0.0272 (g, 361 measurements), 1.0043 ± 0.0083 (r, 1,380), 0.9876 ± 0.0077 (i, 1,465), and 0.9973 ± 0.0082 (z, 1,381). Events overlap between bands, so these are not four independent confirmations. The event-averaged unweighted width RMSE is 0.1531 for w=1+z and 0.5870 for w=1. The comparison favors stretching within the released measurement pipeline; it cannot distinguish expansion from another mechanism giving the same w(z).')
p('Crucially, these widths use reference curves constructed with an assumed dilation correction. The source paper calls this method partly a consistency check and supplies a separate scatter-minimization test [7]. We have reanalyzed the released widths, not rerun that independent method or reconstructed the photometry. The formal uncertainty must not be extrapolated into a new extreme-significance rejection. The quoted external systematic uncertainty is 0.010 in b. A candidate that changes intrinsic supernova physics requires a new forward analysis.')
p('FIRAS spectral check. We downloaded NASA LAMBDA’s 43-channel monopole product [8]. It contains residuals around a reconstructed 2.725 K blackbody, individual uncertainties and a Galactic template, rather than raw instrument measurements. We fit the released residual column with a temperature perturbation, a y-distortion template and a residual Galactic-template coefficient using diagonal weights. This avoids treating rounded tabulated frequencies and reconstructed intensities as a fresh absolute-temperature calibration.')
eq('ΔIν = Gν (ΔT/T) + Yν y + agal Igal,ν;   Yν = Gν[x coth(x/2) − 4],   x = hν/(kBT).')
p('The fit gives y=(0.093 ± 3.611)×10⁻⁶, ΔT/T=(0.184 ± 3.008)×10⁻⁶, agal=−0.00229 ± 0.03243 and χ²=45.02 for 40 degrees of freedom. Errors are conditional on diagonal weights and the selected nuisance templates. Full channel covariance, calibration and foreground uncertainties are not reconstructed; this calculation does not supersede published FIRAS limits. It finds no significant distortion of the fitted type. A temporal transport law that preserves a Planck spectrum is spectrally degenerate with an ordinary blackbody once the present temperature is chosen. This dataset alone cannot measure κ or the radiation’s origin.')
h('10. Screened propagation and conservation in fixed space')
p('A concrete geometric-optics construction addresses the previously unresolved endpoint issue. Let n(x,t)=1+γ(t−tref)f(x), with smooth f=0 at the emitter and detector and f>0 in between. Source and detector therefore retain n=1, while the intervening response evolves. This is a prescribed background; no matter-dependent field equation has yet been shown to generate it. It does not assert that arbitrary screening boundaries cancel no effects.')
eq('dt/dx = n/c₀;   d ln ω/dx = −(∂n/∂t)/c₀ = −γf(x)/c₀.')
eq('ln S = (γ/c₀)∫f(x)dx;   dtarrival/dtemission = exp[(γ/c₀)∫f(x)dx] = S.')
p('The frequency equation follows from the local Hamiltonian ω=c₀|k|/n(x,t); differentiating the ray-arrival equation gives the interval Jacobian. Thus a time-varying interior can redshift and stretch a signal even with equal endpoint response. Static interfaces alone would not do so. For a 100 Mly toy path with f=sin²(πx/R), the active fraction is 1/2. Choosing the local γ to be twice the fitted mean gives S=1.0077614617908. Numerical characteristic integration gives a pulse stretch of 1.0077614617954 and a frequency stretch of 1.0077614617909, agreeing to better than 5×10⁻¹² relatively. These are synthetic consistency results, not astronomical measurements. The pulse offset is dimensionless 10⁻⁴ in units of R/c₀, selected for stable numerics; the Jacobian applies to sufficiently short signals.')
p('This construction leaves a real degeneracy: only γ times the active path fraction is measured by a uniform-distance fit. Smooth screening, negligible reflection, achromaticity and adiabatic evolution are assumptions. Atomic energy levels, interface transmission, polarization and detector calibration require a microscopic treatment. In the earlier unscreened Coulomb interpretation, fixed particle constants with ε∝n give atomic frequencies proportional to n⁻² and can reverse the intended spectroscopic shift. Equal endpoint n avoids that particular endpoint mismatch within the prescribed model, but does not prove a consistent material theory.')
p('Energy conservation is imposed by ∂t uγ+∇·Fγ=−Q and ∂t uχ+∇·Fχ=+Q. A locally thermal present radiation bath at 2.72548 K has ordinary local energy density 4.17×10⁻¹⁴ J/m³ [9]. Coupling all of it at the fitted present fractional rate gives Q≈1.02×10⁻³¹ W/m³. This is an energy-accounting estimate, not a measurement of the field. Its accumulated energy, pressure, backreaction and compatibility with static geometry must be solved. Atomic clock bounds apply to specified dimensionless couplings: if α̇/α=qγ, the measured (1.0 ± 1.1)×10⁻¹⁸ yr⁻¹ implies approximately |q|≲4.1×10⁻⁸ [10]. A common clock rescaling is not constrained this way; ε∝n and c∝1/n can cancel in α.')
h('11. Thermal history and directional structure without a Big Bang')
p('No expanding geometry or singular beginning is required as an assumption of this section. In a homogeneous, adiabatically varying optical response, occupation numbers at fixed wave vector can remain conserved while ω∝1/n. A radiation bath that is initially thermal then retains a Planck occupation law with T∝1/n. The changing density of modes gives photon density proportional to n³T³ and energy density proportional to n³T⁴. Consequently photon number in fixed volume stays constant and radiation energy decreases as 1/n. This is preservation of an existing thermal bath, not creation of one or a prediction of today’s 2.725 K temperature.')
p('The conditional relation T(z)=T₀(1+z) gives 20.005 K at z=6.34, within the published 16.4–30.2 K one-standard-deviation interval from water absorption [11]. This is a summary-measurement comparison; the molecular excitation spectra were not refitted. A constant-temperature background does not match that interval under the published excitation model. Changing atomic or molecular physics requires recalculating the inference. The screened spatially varying construction of Section 10 and the homogeneous thermal argument are not yet a combined global solution: paths with unequal histories, mode transport and detector boundaries can alter the measured spectrum.')
p('An earlier thermal equilibrium in fixed space, continuous field-mediated equilibration and a thermalizing finite boundary are separate hypotheses. The first can preserve a thermal initial condition; the others require collision terms, photon creation or absorption, detailed balance and an energy supply. A compact boundary-free space does not thermalize radiation merely by recirculating it. No reservoir capacity, cavity radius or thermalization rate has been inferred from these data. Ordinary absorption must also remain consistent with sharp distant images and transient signals. All variants must eventually reproduce the CMB angular spectrum and polarization, not only its mean temperature.')
p('Treating the quadrupole–octopole alignment as a target, a homogeneous field and a perfectly symmetric sphere select no direction [12]. A prescribed perturbation ΔlnS=A₂P₂(r̂·â)+A₃P₃(r̂·â) creates aligned angular components and gives ΔT/T≈−ΔlnS; an illustrative 10⁻⁵ perturbation corresponds to 27.25 μK. This is a parameterized construction, not a prediction of the observed alignment. An even, antipodally symmetric response alone cannot produce an odd octopole. The field’s source, preferred direction, angular coefficients and covariance must be specified before a meaningful sky-map test. No Planck map fit or topology constraint is claimed in this revision. Fitting these free coefficients to the target pattern would not establish the theory; independent directional redshift or polarization predictions are required.')
p('Reproducibility. The extension archive time_theory_revision_data.zip contains downloaded derived measurements, source URLs and hashes, analysis code, event-level CSV exports, numerical results and the paper-edit script. It also includes the preceding nearby-galaxy exploratory checks. The released DES widths inherit their reference-curve assumptions; the FIRAS table inherits calibration and foreground processing. Neither archive represents an untouched blind experiment.')
new=[x for x in doc.element.body if x not in before and x.tag.endswith('}p')]
for x in new:anchor._p.addprevious(x)
# New bibliography entries follow the existing reference list.
for text in [
'[7] White, R. M. T., et al. DES Supernova Program: Slow supernovae show cosmological time dilation out to z~1 (2024). https://arxiv.org/abs/2406.05050 . Derived widths and code: https://github.com/ryanwhite1/DES-Time-Dilation',
'[8] Fixsen, D. J., et al. (1996), with the NASA LAMBDA FIRAS monopole release. Product documentation: https://lambda.gsfc.nasa.gov/product/cobe/firas_monopole_spect.html . Data: https://lambda.gsfc.nasa.gov/data/cobe/firas/monopole_spec/firas_monopole_spec_v1.txt',
'[9] Fixsen, D. J. The Temperature of the Cosmic Microwave Background (2009). https://arxiv.org/abs/0911.1955',
'[10] Lange, R., et al. Improved Limits for Violations of Local Position Invariance from Atomic Clock Comparisons (2021). https://doi.org/10.1103/PhysRevLett.126.011102',
'[11] Riechers, D. A., et al. Microwave Background Temperature at a Redshift of 6.34 from H2O Absorption (2022). https://arxiv.org/abs/2202.00693',
'[12] Planck Collaboration. Planck 2018 results. VII. Isotropy and Statistics of the CMB. https://arxiv.org/abs/1906.02552']:
 p(text,'Reference')
doc.save(source)
print(source)
