from pathlib import Path
from docx import Document
from docx.shared import Pt
import shutil,json
P=Path(__file__).resolve().parent;src=P.parent/'redshift_paper/temporal_redshift_paper.docx'
backup=P/'paper_before_candidate_audit.docx'
if backup.exists():raise RuntimeError('Appendix already staged; restore explicitly before rerunning')
shutil.copy2(src,backup);doc=Document(src)
if any(p.text.startswith('Appendix C. Candidate comparisons') for p in doc.paragraphs):raise RuntimeError('Appendix already exists')
def h(s):doc.add_paragraph(s,'Heading 2')
def p(s):doc.add_paragraph(s,'Normal')
doc.add_page_break();doc.add_paragraph('Appendix C. Candidate comparisons with real observations','Heading 1')
p('This extension retains each proposed formula as a separate branch of a fictional, nonexpanding universe. Agreement, discrepancy and missing predictions are recorded independently. The calculations below use processed observational data and published measurement summaries; the connected-field calculation is synthetic. Redshift and rotation samples were examined previously, so these are exploratory evaluations on the preserved splits, not new blind tests. The accompanying candidate_comparison_report.md and temporal_candidate_audit.zip contain the full methods, scores, source inventory and reproduction files.')
h('C.1 Redshift, direction and source environment')
p('Six variants were fitted on the original 104 training groups and evaluated on the 35 validation and 25 reserved groups. With S=1+z and brightness distance D_L, the exponential full-signal branch uses S=exp(κR), D_L=RS; the homogeneous rolling-history shape uses S=1+κR, D_L=RS; the energy-loss-only branch uses S=exp(κR), D_L=R√S. These flux relations define phenomenological variants and have not been derived for the connected screened-field model. The corresponding reserved root-mean-square redshift errors, expressed as cΔz, are 412.44, 411.54 and 413.47 km/s. The original expanding reference remains at 411.93 km/s [1].')
p('The 0.91 km/s improvement of the rolling shape over the exponential shape is inconclusive: a descriptive sky-tile bootstrap interval for the difference is −3.58 to +1.55 km/s. A four-parameter directional rate k(n̂)=k₀ exp(a·n̂) gives 419.44 km/s. A two-parameter rate depending on standardized log catalog group membership gives 460.11 km/s. An added three-component bulk-velocity term gives 404.73 km/s, but worsens validation performance and has a broad bootstrap interval. None establishes a new directional or environmental law.')
p('The source-group proxy counts catalog entries sharing a group identifier. It is selection dependent and does not measure mass density along a light ray. Its adverse reserved result is a limitation of that extension, not a test excluding foreground screening. Pros of the simple branches are their small parameter count and comparable nearby predictions; cons are distance-calibration dependence and their lack of a unique physical derivation. A genuine path-screening comparison still requires foreground matter information and a derived flux law.')
h('C.2 Whole-signal stretching')
p('Refitting the 1,504 exported DES event averages gives a duration exponent b=1.00288±0.00483 in w=(1+z)^b, with formal diagonal-error uncertainty. Refitting 35 published spectral-aging measurements gives b=0.96644±0.10402 in a=(1+z)^(−b). For the spectral measurements, χ² is 26.95 at b=1 and 150.57 at b=0. These reproduce the prior derived-data results. The whole-signal branches meet this observable requirement; the energy-loss-only branch needs an additional duration mechanism [7,13].')
p('The measurements inherit template and calibration assumptions. DES reference widths are partly a consistency test, and the spectral method also uses calibrated templates. The tests do not distinguish two mechanisms that both predict b=1. No extreme-tail significance or new independent discovery is inferred from these diagonal-error comparisons.')
h('C.3 Light, gravity and clocks')
p('GW170817 and GRB170817A have a published gamma-ray minus gravitational-wave arrival delay of 1.74±0.05 seconds [14]. In the homogeneous n=exp(γt) branch normalized to n=1 at photon reception, a simultaneous gravitational signal traveling at constant c arrives later by R/c−ln(1+γR/c)/γ. At illustrative distances of 30, 40 and 50 Mpc, the differences are approximately 368,000, 654,000 and 1,020,000 years. These are conditional calculations, not a reanalysis of the source distance in modified gravity. They expose a substantial discrepancy for this light-only branch.')
p('Identical light and gravitational-wave propagation removes their differential propagation delay by construction. Under n_GW=exp(pγt), a chosen 10-second delay allowance near p=1 at 40 Mpc requires |p−1| of about 4.83×10⁻¹³ in this particular history. This is a sensitivity estimate, not a measured confidence interval. Shared propagation remains a useful extension, with the cost that its gravitational coupling and material-clock behavior must be derived consistently.')
p('Galileo measurements give a fractional deviation from ordinary gravitational redshift of (0.19±2.48)×10⁻⁵ [15]. Separately, explicitly assuming α̇/α=q_eff γ and using the published atomic-frequency comparison yields an approximate |q_eff| requirement below 4.08×10⁻⁸ [10]. A millionfold suppression is insufficient if the intrinsic α coupling is unity, whereas 10⁻⁸ suppression gives a predicted drift within the quoted uncertainty. These constraints apply to the specified couplings, not to every universal rescaling of time; α may remain constant in other constitutive completions.')
h('C.4 Microwave spectrum, temperature and angular structure')
p('The 43-channel FIRAS residual reanalysis gives approximate χ²=45.02 for a single thermal spectrum with temperature and Galactic-template nuisance parameters. Equal-weight mixtures at temperatures T(1±δ) give 45.03 for δ=0.001, 46.51 for δ=0.003, and 235.84 for δ=0.01. These diagonal-error fits constrain the chosen mixture of received temperatures; they are not general bounds on thermalization or a new absolute CMB-temperature measurement [8]. Coherent temporal cooling remains attractive because it can preserve an existing thermal occupation distribution. Its limitation is that it does not explain the initial radiation or select its temperature.')
p('At z=6.34, the published HFLS3 excitation analysis gives 16.4–30.2 K at one sigma. T(z)=2.72548(1+z) predicts 20.005 K, whereas a locally constant 2.72548 K branch lies outside that interval [9,11]. This comparison inherits the source-excitation and molecular-physics assumptions. The screened optical model must also derive the received intensity: in a homogeneous fixed-volume medium with ω=ck/n, mode counting gives uγ proportional to n³T⁴, not the vacuum coefficient held unchanged.')
p('New official Planck bandpower downloads contain 83 TT and 66 EE measurements. Of these, 81 TT bins and 46 EE bins exceed zero by five quoted errors. A strictly homogeneous scalar acting on an initially uniform, unpolarized sky leaves those fluctuations unexplained. Its diagonal χ² diagnostics are about 715,129 and 54,425; the released fitted reference curves give 65.12 and 62.90. These are not the full Planck likelihood and are not converted to extreme-sigma claims [17].')
p('The binned spectra begin near multipole 48, discard orientation information, and cannot test quadrupole–octopole alignment. A preferred-axis or spherical-topology branch is retained, but no axis fit is claimed. It requires explicit direction, amplitude, angular covariance and polarization predictions. Matching the mean temperature alone does not meet those requirements [12].')
h('C.5 Galaxy rotation and density suppression')
p('Two new SPARC templates use v_pred²=v_bar²[1+B/(1+(Σ_star/Σ_*)^q)], with Σ_star=0.5 SB_disk+0.7 SB_bulge. This is stellar surface density, not gas-inclusive volume density. Parameters were fitted on the original 89 training galaxies; quality cuts, mass-to-light ratios, inclinations and distances were held fixed. On the original 31 reserved galaxies, the q=1 version gives a galaxy-weighted speed RMSE of 29.25 km/s and the fitted-q version 28.19 km/s. The baryonic baseline gives 47.77, the earlier acceleration-power branch 17.20, and the RAR benchmark 16.40 km/s [16].')
p('The density templates improve substantially on the baseline but underperform acceleration dependence. The fitted-q minus power log-RMSE difference has a descriptive galaxy-bootstrap interval of +0.00255 to +0.02678 dex. Power versus RAR remains inconclusive. The 11-galaxy subset with non-Hubble distance methods preserves the same broad ranking. These are empirical force-enhancement templates; they do not establish a pure apparent-clock explanation or follow from the optical field equations.')
p('Two consistency requirements remain. A common wavelength multiplier on approaching and receding sides cancels in normalized Doppler splitting, so a timing explanation must derive the actual spectroscopic observable. Also g_extra=A a_K(g_bar/a_K)^p, with a_K=c²κ, contains a free amplitude that absorbs a change in κ. Consequently, the present use of the redshift scale does not independently unify rotation and redshift. The earlier cliff extension remains archived, with its coefficient reaching the imposed upper bound in every fold; no new lensing calculation is claimed.')
h('C.6 Connected fields and conserved energy')
p('A new synthetic calculation joins dense regions and a void in a periodic one-dimensional box. Two fields have positive kinetic, gradient and quadratic coupling energies. A density-dependent term suppresses the optical field χ. A finite-width ray surrogate has Hamiltonian Hγ=p exp(−χbar), with χbar a Gaussian field average of fixed width 0.02 box lengths. Differentiating the same Hamiltonian supplies the ray equations and energy deposited in the fields. This is an effective numerical model, not a covariant electromagnetic or gravitational action.')
p('At 321 sites per field, the negligible-backreaction frequency stretch is 1.003080703 and the pulse stretch 1.003080705, agreeing relatively to about 2×10⁻⁹. The redshift changes by about 0.19% between 161 and 321 sites. With an initial packet energy of 0.1% or 10% of the field energy, the 321-site factors become 1.00335034 and 1.02987139. Photon energy decreases while the combined field-plus-packet energy is conserved to below 10⁻¹² relatively in these runs. The higher-backreaction redshift still changes about 2.1% under the last grid refinement.')
p('The benefit is a concrete conservative mechanism producing redshift and matching event stretching across an inhomogeneous connected system. The limitations are equally concrete: the physical field-energy scale and packet prescription are uncalibrated; matter motion, gravity and atomic clocks are absent; and shifts depend on epoch. At later launch time 40 in the same dimensionless system, the 161-site factor is 0.99647533, a blueshift. A stable finite-epoch mechanism is therefore demonstrated, while a perpetual monotonic cosmic history is not. The initial grid-tied packet variant and the corrected fixed-width variant are both retained in the archive.')
h('C.7 Interpretation and remaining predictions')
p('Every branch is retained with its strengths, discrepancies and required extensions. The completed work consists of the specified observational comparisons and the connected mathematical experiment. It does not include a full foreground-path screening fit, an orientation-sensitive CMB map likelihood, a derived lensing law or a complete microwave-radiation origin model, because those predictions remain undefined. A later extension must preserve its predecessor and state what additional freedom it introduces. The full report and reproducibility package provide the candidate scorecard, exact parameters, per-object predictions, source data and verification results.')
h('Additional references for Appendix C')
for s in [
'[13] Blondin, S., et al. Time Dilation in Type Ia Supernova Spectra at High Redshift (2008), Table 3. https://arxiv.org/abs/0804.3595',
'[14] LIGO Scientific Collaboration et al. Gravitational Waves and Gamma-rays from a Binary Neutron Star Merger: GW170817 and GRB170817A (2017). https://arxiv.org/abs/1710.05834',
'[15] Delva, P., et al. Gravitational Redshift Test Using Eccentric Galileo Satellites (2018). https://doi.org/10.1103/PhysRevLett.121.231101',
'[16] Lelli, F., McGaugh, S. S., and Schombert, J. M. SPARC: Mass Models for 175 Disk Galaxies (2016). https://arxiv.org/abs/1606.09251',
'[17] Planck Collaboration. Planck 2018 results. V. CMB power spectra and likelihoods (2020). https://doi.org/10.1051/0004-6361/201936386 . Official products: COM_PowerSpect_CMB-TT-binned_R3.01.txt and COM_PowerSpect_CMB-EE-binned_R3.02.txt, https://pla.esac.esa.int/ .']:
 doc.add_paragraph(s,'Reference')
doc.save(src)
print('Updated',src,'paragraphs',len(doc.paragraphs))
