from pathlib import Path
from docx import Document
import json
P=Path(__file__).resolve().parent;f=P.parent/'redshift_paper/temporal_redshift_paper.docx'
d=Document(f)
assert not any(p.text.startswith('Appendix H.') for p in d.paragraphs)
d.paragraphs[2].text='Research hypothesis • Revised 9 September 2026 • Interaction and stability extensions'
d.paragraphs[4].text=('We investigate a physically nonexpanding universe with conditional temporal redshift 1+z=exp(κr). Multiplicative composition fixes this form but neither determines κ nor establishes a microscopic interaction. The preserved 164-group experiment uses 104 training, 35 validation and 25 final-test objects. Its fitted κ=7.7314966×10⁻⁵ per million light-years gives final-test redshift RMSE 412.441 km/s versus 411.934 km/s for the specified expanding reference, an unresolved difference. The explicit matter–light interaction fails intended exact atomic invariance: preserving leading optical binding changes hyperfine response. A compensating magnetic moment repairs only the leading term. Shared photon/tensor propagation remains a replacement requirement; universal conformal coupling protects local matter physics but cancels homogeneous redshift when material geometry is static. The fixed flat brightness law develops a significant correlated residual trend in 960 higher-redshift supernovae. Fitting negative curvature improves χ² from 898.5 to 873.0, while positive curvature prefers the flat limit; no compatible stable nonexpanding solution has been demonstrated. In Einstein gravity, the preferred static negative curvature requires negative total enthalpy, which a minimally coupled P(φ,X) scalar cannot supply with both healthy kinetic and gradient terms in the tested regime. Five candidate mechanisms remain documented. Processed duration data favor whole-signal stretching, while FIRAS constrains the tested thermal mixtures; neither identifies the field. New toy extensions show that higher spatial gradients plus a restoring term can stabilize one mode, and that thermal relaxation can approach the monopole spectrum but erases distant source contrast if equally strong at optical frequencies. These conditional results do not establish full gravitational stability, atomic protection or a CMB origin. Screening is a historical branch, not an ingredient of the present unscreened candidate. The next milestone remains one explicit nonrotating interaction with protected clock ratios, shared propagation and a stable background, deriving brightness and angular distances together.')
for p in d.paragraphs:
    if p.text.startswith('Using the directly measured Yb+'):
        p.text=p.text.replace('[20]','[10]')
    if p.text.startswith('The next milestone is one explicit nonrotating, unscreened action that preserves the required clock ratios, shares photon/tensor propagation and admits a stable nonexpanding background. Stability'):
        p.text=('The next milestone remains one explicit nonrotating, unscreened interaction that protects the required clock ratios, shares photon/tensor propagation and admits a stable nonexpanding background. Appendices G–H extend the search without claiming that milestone complete: the conformal family cancels redshift in static material geometry, and simple negative-enthalpy scalar dynamics are unstable. A higher-gradient restoring toy mode and frequency-selective thermal relaxation remain possible ingredients, with background and energy-balance constraints unresolved. Luminosity and angular-diameter distances must follow together from the same action, including source and detector calibration. Rotating and circulating-radiation branches remain candidates. No Big Bang is assumed, and no complete CMB or galaxy-dynamics prediction is claimed.')
def p(t,s='Normal'):d.add_paragraph(t,s)
def h(t):p(t,'Heading 2')
def e(t):p(t,'Equation')
d.add_page_break()
p('Appendix H. Alternate-universe variations and coupled tests','Heading 1')
p('New laws are allowed in this fictional setting. Each variation is therefore assessed for its stated behavior, not rejected merely because it differs from established physics. Observed numbers remain real; hypothetical parameters and synthetic stability checks are labeled. These tests explore repairs and their costs rather than silently combining separate successful features into a claimed theory.')
h('H.1 Thermal relaxation operating alongside temporal redshift')
p('Take the existing affine index dn/dt=γ, with material geometry fixed and conserved comoving wavevector k. Let f_k be photon occupation and impose a constant-temperature reservoir with relaxation rate Γ. The explicit toy kinetic equation is:')
e('df_k/dt = Γ[f_eq(k/n,T_bath) − f_k],    r = Γ/γ.')
p('The instantaneous equilibrium is the Planck occupation at wave frequency c₀k/n. Start in equilibrium at n_i=0.5 and evolve to n_o=1. This is a driven reservoir hypothesis, not the earlier claim that redshift alone produces a thermal bath. The exact linear solution is a weighted integral over past equilibrium occupations; Γ transfers both photons and energy. A constant bath temperature assumes an unmodeled reservoir energy balance.')
p('For each fixed r, fit T_bath and a residual Galactic-template amplitude to the same 43 FIRAS residual channels using diagonal uncertainties. χ² is 237.49 at r=100, 47.32 at r=300 and 45.03 at r=1000, compared with 45.02 for the single-temperature limit. A conditional Δχ²=3.841 threshold relative to that limit occurs at r≈264.35, corresponding to a relaxation time of about 48.9 million years at the fixed γ. The temperature is fitted, not predicted, and the threshold is not a full-covariance or boundary-calibrated confidence statement.')
p('Repeating at n_i=0.1, 0.5 and 0.9 gives effectively the same threshold spectrum: at this rate the initial distribution has been forgotten. Doubling the quadrature resolution verifies the computed spectrum. These checks validate the numerical solution and its limited memory sensitivity, not the reservoir’s physical existence.')
h('H.2 A useful failure and a selective repair')
p('For an excess signal above the reservoir background, this kinetic equation gives survival exp(−ΓΔt). The affine redshift law has γΔt=z/(1+z). If the same relaxation rate acts at optical frequencies, a source at z=1 therefore retains only exp(−r/2) of its excess photons. At r≈264.35 this is about 4×10⁻⁵⁸. The uniform-rate reservoir erases distant source contrast; a good monopole fit does not make it viable for visible galaxies.')
p('A frequency-selective reservoir is a retained repair: keep the common coherent propagation rule but make optical thermalization much weaker than microwave thermalization. For an illustrative 99% excess-signal survival target at z=1, Γ_opt/Γ_microwave must be below about 7.60×10⁻⁵ at the threshold rate. This target is a chosen design diagnostic, not a measured cosmic transparency bound. The spectral selectivity, its atomic consequences, and its compatibility with a conserved total energy budget remain to be derived. Selectivity of collisions is distinct from assigning different coherent photon/tensor propagation speeds.')

d.add_page_break()
h('H.3 Higher spatial gradients and a restoring term')
p('The P(φ,X) instability in Appendix G assumes a two-spatial-derivative description. Test a broader one-mode dispersion with a positive kinetic normalization, adding a positive quartic spatial-gradient term and a restoring mass:')
e('ω² = m² − u²k² + k⁴/M²;    min(ω²) = m² − u⁴M²/4.')
p('Here u>0 is the magnitude associated with the negative squared low-frequency sound speed, and M is a crossover scale in units c₀=1. The minimum occurs at k=uM/√2. The quartic term alone stabilizes sufficiently short wavelengths but leaves longer wavelengths unstable. A restoring term makes this toy dispersion nonnegative at all k if m≥u²M/2; strict inequality makes the minimum positive.')
p('For the illustrative choice u=0.1, m/M=0 and 0.003 remain unstable, 0.005 is marginal, and 0.007 gives min(ω²)/M²=2.4×10⁻⁵>0. A 10,001-point grid agrees with the analytic minimum. The relevant minimum is at k/M≈0.0707, below the crossover scale; no ultraviolet completion is inferred from extending the polynomial to arbitrarily high k.')
p('This is a constructive stability result for one assumed quadratic mode, not a stable gravitational theory. The lapse and shift constraints, tensor and other scalar modes, coupling to ordinary matter and the constant negative-curvature background have not been derived from this dispersion. A mass term also conflicts with the simplest exactly affine homogeneous shift-symmetric clock field: with fixed X and a static background, an added potential must have V′=0 along the rolling trajectory, hence cannot independently supply a constant positive V″ over that same interval. Additional derivative coupling or driving would have to resolve that conflict.')
h('H.4 Interpretation and retained branches')
p('The new tests show both useful repairs and their limits. Higher-gradient dynamics can remove the simple scalar-gradient obstruction at the level of a gapped toy mode, while rapid reservoir relaxation can recover a nearly thermal spectrum. Neither solves the whole system: the first requires background-compatible gravitational dynamics; the second requires spectral selectivity and a reservoir energy balance. Atomic protection and a derived shared tensor/photon interaction remain open in both. Rotation and compact recirculating geometry remain optional extensions whose observables must eventually follow from the same interaction.')
p('Reproducibility. The companion alternate_universe_extensions.zip includes the consolidated candidate reports and code, FIRAS input, new extension script and results. DES, FIRAS, clock summaries and previous supernova fits are distinguished from hypothetical dispersion parameters and transmission targets. No new blind data, raw atom–cavity drift fit, angular-size likelihood or CMB anisotropy fit is claimed.','Reference')
h('Additional references for Appendices G–H')
for t in [
'[28] Kennedy, C. J., et al. Precision Metrology Meets Cosmology: Improved Constraints on Ultralight Dark Matter from Atom-Cavity Frequency Comparisons (2020). https://arxiv.org/abs/2008.08773',
'[29] Bettoni, D., and Liberati, S. Disformal invariance of second order tensor-scalar theories: framing the Horndeski action (2013). https://arxiv.org/abs/1306.6724',
'[30] More, S., et al. Modifications to the Etherington Distance Duality Relation and Observational Limits (2016). https://arxiv.org/abs/1612.08784',
'[31] Garriga, J., and Mukhanov, V. F. Perturbations in k-inflation (1999). https://arxiv.org/abs/hep-th/9904176',
'[32] Babichev, E., et al. Stability of a black hole and the speed of gravity waves within self-tuning cosmological models (2018). https://arxiv.org/abs/1712.04398']:p(t,'Reference')
d.save(f);print('Paper updated through Appendix H:',len(d.paragraphs),'paragraphs.')
